#!/usr/bin/env python3
"""Local scorer: score matching_results.tsv against a hidden truth file
(used only with synthetic test data generated by make_synthetic.py).

    python3 tests/score_local.py --matching output/matching_results.tsv \
        --truth tests/dataset/test_hidden_truth.tsv
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.evaluate import macro_f05


def load_ids(path: Path) -> dict[str, set[str]]:
    d: dict[str, set[str]] = {}
    with open(path, encoding="utf-8") as fh:
        r = csv.reader(fh, delimiter="\t")
        next(r)
        for row in r:
            d[row[0]] = {m.strip() for m in row[1].split(",") if m.strip()} if len(row) > 1 else set()
    return d


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--matching", required=True)
    ap.add_argument("--truth", required=True)
    a = ap.parse_args()

    pred = load_ids(Path(a.matching))
    truth = load_ids(Path(a.truth))
    print(f"entities: {len(truth)} | truth matches: {sum(len(v) for v in truth.values())} "
          f"| predicted matches: {sum(len(v) for v in pred.values())} "
          f"| predicted singletons: {sum(1 for v in pred.values() if not v)}")
    print(f"MACRO F_0.5 = {macro_f05(pred, truth):.4f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
